version: '3'
services:
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "3000:3000"
    volumes:
      - $GOPATH/src/paymentapi/apigateway:/apigateway
    networks:
      - payment_api
    working_dir: /apigateway
    command: air

  payments:
    build:
      context: ./payments
      dockerfile: Dockerfile
    container_name: payments
    ports:
      - "3001:3001"
    volumes:
      - $GOPATH/src/paymentapi/payments:/payments
    networks:
      - payment_api
    working_dir: /payments
    command: air

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - payment_api

  wiremock:
    image: wiremock/wiremock:3.9.2
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files  
    environment:
      - JAVA_OPTS=-Xmx1024m
    networks:
      - payment_api

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - payment_api
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  payment_api:
